### ISSUE TITLE
Examples needed for "accountable for delivery" competency

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/engineering-progression#100]
_Opened on behalf of @JakeChampion after we ran through the competencies._

---

**Competency:** `983dd8411-940d-4aa8-9ba6-add04510a7da` (S1→S2, Delivery)
> Is accountable for the delivery of the team, e.g.
>   -  Helps delivery lead write progress reports

Could use examples for teams without a delivery lead. Also on a small team, e.g. Origami, it's difficult for more than one person to be held accountable

Could use examples for teams without a delivery lead.

**Comment by alicebartlett** [comment]
Hmm- this one is tricky. Do either of you have any suggestions?

**Comment by alicebartlett** [comment]
- Writes a monthly update newsletter for stakeholders about recent releases
- Grooms backlog to make sure issues are ready to be picked up

**Comment by lc512k** [comment]
This one came up in the S2 workshop again as needing examples, so the above will help 

It was also mentioned that 'accountable' could be clarified to not mean 'solely accountable' - the examples above might clarify this 

cc @umbobabo 

If there are no objections I'll create a PR for this and tag you all as reviewers. Thanks!
