### ISSUE TITLE
J -> M clarifiction: "Regularly collaborates with team members from other disciplines to deliver features"

### ISSUE THREAD

**Issue by sbinlondon** [Financial-Times/engineering-progression#108]
I was wondering if this would benefit from some examples or clarification.

Does this mean within my actual team, i.e. Envoy, talking to our business analysts and other non-engineers? Or within my department, Internal Product? Does it mean our stakeholders in marketing?

Sorry if *team* means actual *team* but I wanted to make sure it didn't mean something broader i.e. colleagues in general.

**Comment by alicebartlett** [comment]
This competency is about collaborating with anyone in a different discipline. That could be in the immediate _team_ team or it could be within your broader group. 

Is this broader definition a problem in terms of fulfilling the competency?

**Comment by sbinlondon** [comment]
Not at all - I think it's good that it means your immediate team or broader group. It gives more opportunities for people to put it into practice 👍

**Comment by alicebartlett** [comment]
Great, so are you happy for me to close this issue?

**Comment by sbinlondon** [comment]
Yep!
