### ISSUE TITLE
Clarify what we mean by being a "go-to person"?

### ISSUE THREAD

**Issue by jonnangle** [Financial-Times/engineering-progression#117]
- https://github.com/Financial-Times/engineering-progression/blob/master/data/competencies.yml#L637
- https://github.com/Financial-Times/engineering-progression/blob/master/data/levels.yml#L35

> Senior 2 engineers are seen as the go-to person for a particular technology or product.

If we want to encourage this as a behaviour, should we also add something along the lines of "whilst ensuring that they do not accidentally become a key-person dependency"?

**Comment by sjwells** [comment]
Would it be better to change it to say 'have a deep understanding and willingness to help others for a particular technology or product'?

**Comment by wheresrhys** [comment]
From discussion with @Limess

Should this be rephrased to talk about expertise levels in a less exclusive sounding way? The way it's worded feels like a perverse incentive to hoard knowledge.

I like Sarah's rephrasing

**Comment by rowanbeentje** [comment]
@jamesnicholls had the same feedback on this point - I also like Sarah's new wording, James how does that suggestion look to you?

**Comment by jamesnicholls** [comment]
@rowanbeentje yeah, I like it.
