### ISSUE TITLE
Web app for individuals to track their own process

### ISSUE THREAD

**Issue by quarterto** [Financial-Times/engineering-progression#118]
We have the spreadsheet integration, which is cool, but unless I'm missing something, once you've copied the spreadsheet your copy can become stale?

What I'm thinking is a webapp that:

  - has google sign in
  - pulls in data from the JSON API
  - allows you to check off your completed competencies & provide evidence
  - perhaps could talk to People API so it knows what levels you're looking at

This is something that, if there's appetite for it, I am extremely likely to work on as a 10% project. I mean, I'm probably going to work on it anyway because of who I am as a person but if there's some justification for it then great

**Comment by quarterto** [comment]
vvv good point about GDPR, i hadn't considered that, thanks. i'd likely only store competency IDs, completed, and evidence, linked to an internal user ID that could be mapped to an employee's email address, definitely could be sensitive. because i'm structuring it like that the webhook wouldn't be necessary.

i'm not sure how to handle versioning. i'm guessing IDs for competencies would be static between versions? i don't know how the UX would feel for a user to come back to the app and something they've checked off has changed

**Comment by rowanmanning** [comment]
Competency IDs remain the same between versions 👍 though they may be deleted, or new ones added so you'd have to handle that.

If you decided to store a copy of the competencies (versions are immutable) then you could possibly store a copy of _every_ version that's released and then have a little notice to a user that says "switch to the latest version of the competencies". That feels like a bunch more work though.

**Comment by quarterto** [comment]
is the current version available in the API? i don't see it anywhere. i can store the version number from when the user last made a change and notify if the version is different now. storing all old versions feels like a massive can of worms 😬

**Comment by rowanmanning** [comment]
The major version is in the URL (https://engineering-progression.ft.com/api/v1/competencies/all.json), but the _full_ version isn't available right now but we could always add an endpoint for it if you'd find that useful.

**Comment by rowanmanning** [comment]
The version is now visible here:
https://engineering-progression.ft.com/api/v1/version.json

**Comment by mark-barnes** [comment]
@quarterto Bren - just had a brief chat about this with Alice ... feels like your initiative so if it's ok assigning to you.
