### ISSUE TITLE
Do I need to meet 100% of ALL the competencies to be promoted?

### ISSUE THREAD

**Issue by binaryberry** [Financial-Times/engineering-progression#121]
I've read the "how to use the competencies" section (which is good!) but I'm still not sure whether I need to meet all the competencies listed on a sheet of an engineering progression tracker to be promoted.

**Comment by rowanmanning** [comment]
Hi Tatiana, the [section on competencies here](https://engineering-progression.ft.com/competencies/how-to-use/#competencies) does say:

> Engineers are expected to meet all of the competencies for a level in order to be promoted, except for domain-specific competencies that don’t apply to their role or specialism.

but now I read this back to myself it's maybe not clear enough. The answer to your question is yes, you'd need to meet all the competencies for the level you'd like to be promoted into (except domain-specific ones). I'll think about how we can better clarify that in the "how to use" guide, but I'm definitely open to wording suggestions 🙂

**Comment by binaryberry** [comment]
Argh thanks for saying it might not be clear, but re-reading this I don't know how I did not register the meaning when I read it. Totally my bad I think. Ignore this!
