### ISSUE TITLE
S1->S2: Feedback on tech strategy

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#124]
> Considers wider tech strategy when coming up with technical solutions

What does tech strategy mean in this context? Is it _the_ FT tech strategy, or technical strategy in a wider sense?

From discussion with @Limess

**Comment by alicebartlett** [comment]
This has highlighted to me that I don't know what the broad FT tech strategy is.
I know what the customer products tech strategy is, which I _think_ is what I meant when I wrote it. Do other Groups have a tech strategy that is understood by the people in the teams?

**Comment by alicebartlett** [comment]
[3/5/19]
- An engineer in Customer Products knows how their work feeds in to the Customer Products tech strategy
- something about cost? @lc512k to pick up
