### ISSUE TITLE
S1->S2: Too much overlap between cross-team working competencies?

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#125]
> Technical: Finds technical problems outside of immediate team and identifies ways to improve them

> Communication: Works cross-team to join up technical gaps

> Delivery: Works with other teams to deliver shared outcomes

> Delivery: Tackles complex cross-team technical issues breaking them down into smaller bits and addressing them

The four competencies above feel like they overlap somewhat, particularly the last 3.

From discussion with @Limess

**Comment by alicebartlett** [comment]
I don't think some overlap is a problem, but you're right in that it is difficult to see why these four competencies exist, especially as none of them have examples.

## My proposal
Remove _Delivery: Works with other teams to deliver shared outcomes_ entirely.
Remove _Communication: Works cross-team to join up technical gaps_

Add clarifying examples to the remaining two which I do think are distinct:
Technical: Finds technical problems outside of immediate team and identifies ways to improve them
* **Notices a lot of requests coming in to Ops Cops from Customer Support for an admin task that could be automated. Automates the task and works with the Customer Support team on how to use the new tool.**
* **While debugging an issue, traces the bug back to a shared library. Creates a patch for the bug and makes sure it is released.**

Delivery: Tackles complex cross-team technical issues breaking them down into smaller bits and addressing them
* **Manages the roll out of a new shared tool to multiple code repositories, identifying what work needs to be done, and finding teams to do the work**


What do you think @wheresrhys @Limess

**Comment by lc512k** [comment]
@sjparkinson pointed this out in our session yesterday as well. Sam, what do you think of the above?

Will make a PR shortly and tag you all if there are no objections cc @Limess @wheresrhys

**Comment by sjparkinson** [comment]
Yep, and really like that delivery example. The last point is helpful.

**Comment by sjparkinson** [comment]
Related issue that this will address, https://github.com/Financial-Times/engineering-progression/issues/99.

**Comment by lc512k** [comment]
addressed in https://github.com/Financial-Times/engineering-progression/pull/161
