### ISSUE TITLE
M->S1: Feedback on Observability

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#128]
> Implements observability and monitoring when building a solution

Does this mean doing this in a self-directed way the work i.e. identifying what monitoring is appropriate and implementing it, or implementing what a tech lead decides is the correct level of monitoring?

From discussion with @ericanand

**Comment by alicebartlett** [comment]
[3/5/19 issue squashing catch up]
We mean that someone implements observability and monitoring and they understand what is an appropriate level to add. As with most developer work, there will be conversations with their team about what to build and why.

@wheresrhys to reword.

**Comment by wheresrhys** [comment]
PR https://github.com/Financial-Times/engineering-progression/pull/144
