### ISSUE TITLE
M->S1: Feedback on communicating to non-tech

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#129]
> Communicates technical concepts to non-technical people clearly

In some, mainly tech-facing teams, formal interaction with non-tech is relatively rare below senior/principal level; compare e.g. an ft.com developer working side by side with designers on a daily basis, and a cloud engineer only dealing with other engineers.

Could the phrasing if this competency by widened to include communicating cross discipline within tech, or communicating with others with less expertise (proto-mentoring)?

From discussion with @ericanand

**Comment by sjwells** [comment]
How about "Communicates technical concepts clearly and adapts that communication to the audience, e.g.  can explain technical concepts to non-technical people, can tech them to more junior people"
