### ISSUE TITLE
M -> S1: Duplication of text

### ISSUE THREAD

**Issue by lucas42** [Financial-Times/engineering-progression#130]
There's two bits of the M->S1 competencies which mention "Communicates technical concepts to non-technical" people/colleagues.

Personally, I think this makes more sense in Communication than under Leadership, but either way, it probably shouldn't be in both.

**Comment by rowanmanning** [comment]
Ah yep, I'm sorting this now. Most of the "communicates technical concepts" issues are a little messy and need refining. See here for an overview: https://github.com/Financial-Times/engineering-progression/issues/96#issuecomment-486654680

**Comment by rowanmanning** [comment]
Hopefully #138 fixed this, let me know what you think @lucas42

**Comment by lucas42** [comment]
It's much  clearer, thanks 👍 

Though now there's nothing in S1->S2 about translating technical info to a non-technical audience.  Are competencies assumed if mentioned in a lower promotion tier (in this case M->S1), or does it need explicitly called out?

**Comment by rowanmanning** [comment]
Ah yes, it's generally assumed that people are meeting the competencies for the levels below them if they go for a promotion. Though we don't explicitly say this anywhere. I've opened #140

**Comment by jenniferemshepherd** [comment]
The version I have of this (which I just took from the microsite still has the duplication "Presents aspects of their work to stakeholders"?

**Comment by rowanmanning** [comment]
Hi @jenniferemshepherd, I _think_ we hadn't tagged up a release at that point. I released `v1.0.0-alpha.13` this morning, could you check again now?
