### ISSUE TITLE
M -> S1: Are guilds still a thing?

### ISSUE THREAD

**Issue by lucas42** [Financial-Times/engineering-progression#131]
A couple of the examples in M->S1 mention guilds.  I know the FT has spent years trying to get guilds to happen, but other than a couple of small examples, they've not really taken off.

Perhaps we shouldn't focus on them so much in the examples?  Sure, if someone has been involved in a guild that can be used for any appropriate competencies.  But putting them in the examples, when a large proportion of people have never been involved in one, puts the emphasis in the wrong place.

<img src="https://user-images.githubusercontent.com/428847/56598021-8daa9f00-65eb-11e9-9c23-d13b1b1b7aa8.jpg" width="250" alt="Stop trying to make guilds happen">

**Comment by alicebartlett** [comment]
OK - I think we can remove guilds examples, what's everyone else think?

**Comment by JakeChampion** [comment]
+1 on removing the guild examples

**Comment by alicebartlett** [comment]
@lucas42 can you provide any examples to replace the guild examples in either of these?:


>id: f34273e2-3d81-4bde-8c23-0217e71b3536
  summary: Influences a community of practice
  examples:
    - **Is an active member of a Guild**
    - "Answers questions in the #engineering Slack channel"
  description: null
  level: mid-to-senior1
  area: leadership
  domain: null

>id: 2c9171a0-8935-41fa-809e-08c311538eac
  summary: Shows technical leadership
  examples:
    - Is a tech lead
    - **Runs, or is on the organising team for a Guild**
    - Leads on large features or stories
  description: null
  level: mid-to-senior1

**Comment by alicebartlett** [comment]
[3/5/19 issue squashing catch up]
If someone is an active member of a guild they mwould still meet this competency so not going to remove these. Came up with some other examples for the first competency though so will add those. 

- Gives a tech talk internally or externally
- Writes a blog post
