### ISSUE TITLE
Add notes on meeting competencies from other levels

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/engineering-progression#140]
The how-to-use guide on the website should mention meeting competencies from lower levels. A promotions case doesn't need to include evidence for levels beneath you, it's just assumed that by being in that role you're meeting the competencies from the level below, or are _able_ to.

Possibly this needs some discussion, I can anticipate a few questions around this.

**Comment by alicebartlett** [comment]
Let's add an FAQ once #168 is merged
