### ISSUE TITLE
Clarifies what "Contributes to hiring process" entails

### ISSUE THREAD

**Issue by binaryberry** [Financial-Times/engineering-progression#146]
While reading that competency, in the mid to senior sheet, I assumed the only things that would count were interviewing and attending hiring events. Do other contributions such as public speaking, tweeting about hiring, going to a tech event and making an announcement saying we're hiring count?

**Comment by alicebartlett** [comment]
Yes I think all of these count.
I think this competency is quite flexible and should allow people to complete it in a way that they feel comfortable. The hiring process goes from "getting people interested in working at the FT" all the way through to interviewing them. Some people will be more comfortable reviewing CVs or tech tests, than say, standing up at a meet up and saying "we're hiring, please come chat to me about what it's like to work at the FT". Perhaps we could add more examples to this:

- Publicly sharing links to open roles
- Going for coffee with potential hires to talk about what working at the FT is like
- Sharing our work publicly (blog posts, talks, etc) so people can see the kinds of work we do here
- Reviewing CVs
- Reviewing tech tests

@Financial-Times/engineering-progression-working-group are we on the same page on this?

**Comment by alicebartlett** [comment]
Stand by: going to open a PR
