### ISSUE TITLE
Review language / examples for "leads on", "takes responsibility for" and "coordinates"

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/engineering-progression#150]
A few people have fed back to us that they don't know what "leads on" means, similarly with "coordinates" and "takes responsibility for". We should review where these terms are for and make sure there are examples, or enough clarity around how to meet these.

**Comment by wheresrhys** [comment]
Uses of 'leads on' in competencies is now well covered by examples for the most part, with the following exception
- 07715459-0423-4507-bdf1-fc397507eec7 (Leads on fixing production issues) - a separate issue #195 has been opened for this.

'coordinates' is not used anywhere

'takes responsibility for' is used once, but #153 already discusses changing that competency significantly.

As a general point, we prefer to use examples to clarify intent. It feels like a more reliable and user friendly way to communicate what we mean than to expect that nuances of how a particular term is used will be clear to everyone.
