### ISSUE TITLE
M->S1 Keeps up with industry trends

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/engineering-progression#151]
Lots of feedback on this competency from the workshop. Some quite valid points but some reasonable counter arguments too. Opening this up for further discussion:

- Implies outside work activity?
- Can be good senior without
- Overlap with evaluating 3rd party software/pick right tool - being aware of industry trends is part of evaluation
- Feeds into being a domain expert (is there a competency that captures this)
- Suggest this competency is ditched

**Comment by rowanmanning** [comment]
I'm not against removing this competency, but we could maybe reflect the intent in the examples of other competencies. Possibly:

  - Add an example to *Learns and improves independently* _(`22c2a49e-4e2e-4a63-a09e-57a0efce7e38`)_ around reading articles during down-time at work?
  - Add an example to *Takes ownership of personal development* _(`f6e9efd1-7d55-439b-8f7d-c50829e48879`)_ about asking to attend conferences that are relevant to their job
  - Add an example to *Influences a community of practice* _(`f34273e2-3d81-4bde-8c23-0217e71b3536`)_ about sharing interesting and relevant links to talks/blog posts
