### ISSUE TITLE
Add clarifying examples to "Team ambassador" M->S1

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/engineering-progression#152]
This competency is about understanding that your individual actions reflect on your team. I think we could add some examples like:

- Is courteous to members of other disciplines, seeks to understand their perspectives, values and needs
- Seeks to understand why a problem exists instead of blaming another team for it

I don't know... something like this... help me out @lc512k !

**Comment by wheresrhys** [comment]
Fixed by #164
