### ISSUE TITLE
M->S1: split code quality competency into separate code review and code quality ones

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#153]
> Takes responsibility for code quality by keeping the quality high and encouraging others in the team to do the same

Is far longer than most competencies, and feels broader.

Suggestion:

Split into 2 competencies (wording and examples to be developed further)
- Delivers high quality code and solutions (this develops the J->M "Uses a programming language to make something")
	- Implements tooling to enforce high standards
	- Refactors solutions to improve clarity and maintainability
 	- ...
- Gives clear and actionable technical feedback
	- Reviews pull requests fairly & critically in such away that team members produce better code
	- Contributes to technical discussions designing a new feature/system

**Comment by lc512k** [comment]
Addressed in https://github.com/Financial-Times/engineering-progression/pull/201
