### ISSUE TITLE
Relative importance of competencies

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/engineering-progression#156]
The S2 workshop raised the difficulty of knowing which competencies where more important than others, to help the person going up for promotion prioritize what they'll focus on.

The discussion that followed centered around having to do them all for promotion (unless one is clearly not applicable) and that it may be up to the manager and report to decide amongst themselves what the priority for achieving them should be, but worth opening it up for discussion briefly to see if anything needs to change.

@sjparkinson @Financial-Times/engineering-progression-working-group

**Comment by lc512k** [comment]
@sjparkinson given the [docs](https://engineering-progression.ft.com/competencies/how-to-use/) and the workshop discussion are you happy with encouraging managers/reports to prioritise themselves, while knowing that all of the competencies need to be met?

**Comment by sjparkinson** [comment]
Yep, that's understandable.
