### ISSUE TITLE
S1->S2 What about individual contributors

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/engineering-progression#157]
The question of individual contributors (engineers who would like to progress past S1 without managing others) came up. 

The discussion that followed emphasised that while not every S1 who wants to go up for promotion needs to have tech lead a team, the element of bringing other people up (there are multiple ways to do this) is mandatory.

@umbobabo suggested that making it explicit somewhere that you don't have to do all the examples would help here. 

We went straight into the competencies during the session but this is clarified here https://engineering-progression.ft.com/competencies/how-to-use/#examples @umbobabo does this help?

**Comment by umbobabo** [comment]
Thank you @lc512k. It does help so I think there is nothing to change in this part. Due to this, I close the issue.
