### ISSUE TITLE
S1->S2 public speaking

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/engineering-progression#158]
The question of "does everyone need to do public speaking? Doesn't that put introverts at a disadvantage?" came up.

There seemed to be a lack of clarity in the fact that examples are illustrative and that they don't all need to be met by candidates for promotion

This page helps https://github.com/Financial-Times/engineering-progression/issues/157 but it can be easily skipped

Do we need to make the `read how to use them here` link more prominent somehow in https://engineering-progression.ft.com/competencies/ ?

cc @umbobabo

**Comment by rowanmanning** [comment]
Is this a possible duplicate of #149?
