### ISSUE TITLE
Clarify that you can still be promoted if a competency doesn't apply to you

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/engineering-progression#159]
@joannaskao mentioned that if a team doesn't have recruitment for a year and during that time someone is going up for a promotion they won't have had the opportunity to recruit. 

I believe this has come up for Origami or Labs cc @rowanmanning ? Will close if duplicate or already addressed.

The suggestion was to clarify this. The table at the bottom of https://engineering-progression.ft.com/competencies/how-to-use/#competencies probably does this. Does this help @joannaskao ?

**Comment by joannaskao** [comment]
I think as long as it's clear that it doesn't count against you, I think that works (I found the table at the bottom useful for this, so I don't know if it needs much improvement if you assume people read the "How to use" page first). 

Somewhat related, but this competency could probably use an example — in a team with with multiple seniors, it would be difficult for everyone to get a chance to lead on hiring if there's only one person getting hired. But perhaps explaining that leading on part of the process counts, that might be useful?

**Comment by alicebartlett** [comment]
Going to open a PR to clarify the leading point as per your suggestion Joanna
