### ISSUE TITLE
[M->S1 workshop] Gets involved in fixing production issues - what does "production issue" mean?

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/engineering-progression#170]
> Gets involved in fixing production issues

Clarification / Examples over what "production issue" means

**Comment by alicebartlett** [comment]
This is about fixing `live incidents in production`, not simply bugs

- Notices that an AWS region is down so fails over to another region
- etc

**Comment by lc512k** [comment]
addressed in https://github.com/Financial-Times/engineering-progression/pull/191/
