### ISSUE TITLE
[M->S1 workshop] Provides feedback on peer’s work

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/engineering-progression#173]
> Provides feedback on peer’s work, e.g.
> * Reviews pull requests and gives actionable empathetic feedback

The M->S1 workshop raised that this might be very hard for a junior to do. As this has been raised it tells me there is room for clarification on this competency, however I don't want to remove it or change the bit about Pull Requests because:

- there should always be PRs around that are clear enough that a Junior Engineer could review them, for example copy changes, tweaks to style, package bumps
- this progression does not state the person should be the only reviewer - chipping in with someone else is fine.

**Comment by alicebartlett** [comment]
Reword to:
> Provides feedback on peer’s technical work, e.g.
> * Reviews pull requests and gives actionable empathetic feedback
> * Speaks up when they don't understand what some code is doing <- not sure about the wording on this
> * Gives realtime feedback in mob programming sessions

**Comment by wheresrhys** [comment]
for the second example:

- Recognises when a more senior colleague has not given enough detail in an explanation, and asks for clarification

How's that?

**Comment by lc512k** [comment]
addressed in https://github.com/Financial-Times/engineering-progression/pull/200
