### ISSUE TITLE
[M->S1 workshop] Leads on getting well defined tasks from backlog to production

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/engineering-progression#174]
> Leads on getting well defined tasks from backlog to production, e.g.
> * Turns a user story into a technical implementation in production

Does this mean "can mostly work on a task by themselves"? (Another example needed)

**Comment by alicebartlett** [comment]
Basically, yes that is what we mean, however there are some scenarios where it is appropriate to ask for help.

Reword + example:
_Is accountable_ for getting well defined tasks from backlog to production, e.g.
* Turns a user story into a technical implementation in production
* Raises blockers in timely way

@cebirmingham is this clearer?

**Comment by cebirmingham** [comment]
yes that's clearer, thanks

**Comment by alicebartlett** [comment]
Thanks charlotte - I will PR
