### ISSUE TITLE
[M->S1 workshop] Leads on getting well defined tasks from backlog to production

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/engineering-progression#175]
"Is there anything about confidence of delivery? At junior it was more about what ticket can I do? Now the emphasis seems to be I'm now able to take any ticket and work on it. (Is there any way we can add this?)"

Raised by @katiekoschland in the mid level workshop. I think this needs more discussion. Katie do you have time to elaborate further on this point?

**Comment by alicebartlett** [comment]
@katiekoschland do you have time to look at this? We'd like to get it in for the beta, which ships end of q2

**Comment by katiekoschland** [comment]
I am happy to close this issue as I have had a look over the competencies again and feel that my point is captured in the checklist.
