### ISSUE TITLE
Acts on feedback competency relies on feedback being given

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/engineering-progression#180]
**Competency:** `d31a91de-ae96-457c-9ac1-3752acf148fa`
**Summary:** <q>Receives feedback and acts upon it</q>
**Examples:** none

It was highlighted that 360 feedback happens twice a year, and some of the juniors feel that they don't often get actionable feedback from their team day-to-day. Maybe some examples on this to illustrate what feedback can look like would be helpful. E.g implmenting changes given in a code review, not just end of year feedback.

---

_Raised during the junior engineer focus group_

**Comment by alicebartlett** [comment]
*Summary*: Receives feedback and acts upon it
*Examples*:
- Implements requested changes on a pull request
- Responds to comments on a google doc
- Receives feedback that they don't seem well prepared for morning stand-ups, so takes 5 minutes before stand-ups to gather thoughts about what the status of their work is before the stand-up starts

**Comment by rowanmanning** [comment]
Looks good, better than what we have 👍
