### ISSUE TITLE
Potential difficulty meeting "gives timely actionable feedback" competency

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/engineering-progression#181]
**Competency:** ` 79c4ecfd-7085-49c2-8a21-429b4a269c96`
**Summary:** <q>Regularly gives timely actionable feedback to colleagues</q>
**Examples:** none

This one sparked a lot of discussion, I think direct quotes are probably best:

  - <q>This one may be a bit more difficult because as a junior you may not feel comfortable giving feedback to your colleagues if they are more senior.</q>
  - <q>In my team there are 3 seniors and a junior and I would find it very difficult to give feedback to a more senior member of staff.</q>
  - <q>Maybe this is a cultural thing between different teams</q>

Is this maybe a difficult competency for somebody who's more introverted, or working on a much more senior-heavy team?

---

_Raised during the junior engineer focus group_

**Comment by alicebartlett** [comment]
I think we could clarify this to state that -
* Feedback can and should be both things that people are doing well, and things they could improve for next time.
* Feedback doesn't need to be direct, it can go via a line manager

Could some examples help with this?

*Summary*: Regularly gives timely actionable feedback to colleagues
*Examples*:
- Sends positive feedback to a colleagues line manager when they have been especially helpful.
- Notices that someone in the team has invited everyone to a meeting without an agenda. Asks them to add one.

**Comment by rowanmanning** [comment]
I think your suggestions are good, Alice 👍
