### ISSUE TITLE
Engineering progression criteria is way too broad and does not differentiate between various engineering flavours

### ISSUE THREAD

**Issue by krumft** [Financial-Times/engineering-progression#182]
The website https://engineering-progression.ft.com/ is titled `Engineering Progression`, but I can't seem to find any contents on that website that is tailored and catered to specific engineering flavours.

Speaking about `engineering` in general is a great first step but it's just that - a first step. We need to provide specific guidance, criteria and examples that define the company's expectations of how a career growth should look like, in the various tracks of engineering - software engineer, operations support engineer, customer support engineer, integration engineer, DevOps engineer, data engineer,  security engineer, site reliability engineer, etc.

Needless to say these are very different roles, and career ladder progression in any one of them inevitably means specialisation and deepening of the expertise, skills and focus in certain areas only, not in all possible aspects of the engineering calling.

There's no such thing as `Engineer` in the industry, so `Engineering Progression` is of little help to employees who are seeking particular guidelines on how to navigate their careers successfully.

**Comment by alicebartlett** [comment]
Hi @krumft, thanks for the feedback.

We have an issue regarding domain specific competencies already, you can see it [here](https://github.com/Financial-Times/engineering-progression/issues/8). Addressing this is in our [Beta milestone (due 30th of June)](https://github.com/Financial-Times/engineering-progression/issues?q=is%3Aopen+is%3Aissue+milestone%3ABeta)

I'm going to close this issue, but please, if you have any ideas for competencies specific to a particular domain add a comment on the original issue. The domain specific competencies will have to be provided by people with expertise in those areas, we're really keen to have your input.
