### ISSUE TITLE
Clearer progression on 'tech direction' competency

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#205]
In S1 -> S2 we have:

> Considers the technical direction of their group or the wider department when coming up with technical solutions, e.g.

S1 workshop felt that:
- at S2, engineers should be having input into shaping the tech direction, not just considering
- at S1 there should be a competency about considering the tech direction
- possibly something at M too, though not sure what this would look like

**Comment by alicebartlett** [comment]
I agree, let's discuss in our 3pm meeting

**Comment by alicebartlett** [comment]
> Considers the technical direction of their group or the wider department when coming up with technical solutions, e.g.
> * Understands how their work feeds into their group's tech strategy
> * Can articulate and justify the total cost of ownership of their technical solutions
> * Follows their group's Engineering Principles when building technical solutions

**Comment by alicebartlett** [comment]
I think this competency is good but we also want to add another about shaping and defining the technical strategy as well as understanding it and acting accordingly

**Comment by wheresrhys** [comment]
Is your proposal to add an extra competency at S1->S2 and keep this one, and do nothing at M->S1?

I would prefer - as in the original issue description - to put something around considering tech direction at M->S1, otherwise we still have nothing about being aware of tech strategy at M->S1. And then at S1->S2 to reword and tweak examples in this competency to make it more about having an input rather than just considering.

**Comment by rowanmanning** [comment]
OK Alice is in agreement now. We've decided to:

1. Move this competency down a level
2. Add a competency at S1->S2 about _shaping_ tech direction
