### ISSUE TITLE
Provide examples for: S1->S2 Translates difficult business requirements into technical designs with stakeholders

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#208]
From S1 workshop:

Both "business" and "stakeholders" are loaded terms (in the workshop several interpretations came up). The wording of the competency isn't terrible, but could definitely do with clarifying examples

**Comment by alicebartlett** [comment]
What were the interpretations of s"takeholders"? Perhaps they're all valid, it would help us come up with examples.

**Comment by wheresrhys** [comment]
> Business requirements
I think the confusion was between 
- Something which is easily expressible as something the business wants to do e.g. reduce friction in signup journey
- Or can it be more broad e.g. provide a testing library that improves dev workflow. It helps the business, but it's more a 'functional requirement' than a business requirement. 
> Stakeholders
I think the confusion was between 
- the people/teams your team build things for 
- people who are closely involved in coming up with the solution e.g. product owner, delivery manager, principal engineer
The feeling was that interaction with stakeholders can, rightly or wrongly, be quite removed from those designing and building the solution. e.g. having all comms channelled through a product owner is not unknown

**Comment by wheresrhys** [comment]
Issue https://github.com/Financial-Times/engineering-progression/issues/244 refers to this competency too.

There is a proposal to remove 'stakeholder' from the competency title, which addresses the second problem. We will also write examples, which will help with the first problem.
