### ISSUE TITLE
S1->S2: Needs comms competency on feedback

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#210]
S1 workshop observed that there is nothing here on delivering feedback and probably should be

**Comment by alicebartlett** [comment]
There are some feedback points in the J->M competency. Do we need to go further than this for S1->S2 or is this sufficient?:

**J->M**
> Provides feedback on peer’s work, e.g.

> Reviews pull requests and gives actionable empathetic feedback
> Recognises when a more senior colleague has not given enough detail in an explanation, and asks for clarification
> Gives realtime feedback in mob programming sessions

And 
**J->M**
> Regularly gives timely actionable feedback to colleagues, e.g.

> Emails positive feedback to a colleague's line manager, after the colleague was especially helpful.
> Notices that someone in the team has invited everyone to a meeting without an agenda. Asks them to add one so people know what the meeting is for and can prepare properly.

**Comment by alicebartlett** [comment]
Let's discuss in our 3pm meeting

**Comment by alicebartlett** [comment]
We also have 

Contributes to the personal development of more junior people, e.g.

> Pairs with more junior team members
> * Mentors people
> * Line manages people
> * Writes blog posts
> * Gives talks at meet-ups or conferences
> * Helps resolve disagreements healthily, e.g.
and
> Helps the team navigate disagreements over the best way to do things. Gets agreement and buy-in from engineers on a solution to a problem
> * Encourages team members to speak freely in retrospectives
> * Encourages team members to treat each other empathetically

**Comment by wheresrhys** [comment]
The conclusion to our discussion of this was that delivering feedback is a tool for achieving other competencies around people skills, so doesn't need to be called out in its own competency. Also, successfully doing the competencies from lower levels around feedback is assumed. Are you happy with this @quarterto @leggsimon @Limess @ookejimift

**Comment by rowanmanning** [comment]
Closing this as it seems like we're in agreement. We can reopen later if necessary
