### ISSUE TITLE
Feedback: S1->S2 Communicates complex technical concepts clearly and adapts that communication to the audience, e.g.

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#211]
From S1 workshop:

The wording of this is almost identical to the equivalent in M->S1, and the examples fro both don't help clarify (e.g. they lean pretty hard on the meaning of terms like 'complex')

**Comment by alicebartlett** [comment]
For context - the full competencies that this refer to are: 

**S1->S2**
> Communicates complex technical concepts clearly and adapts that communication to the audience, e.g.
> * Explains complex technical concepts to colleagues from other disciplines
> * Teaches more junior engineers


**M->S1**
> Communicates technical concepts clearly and adapts that communication to the audience, e.g.
> * Explains technical concepts to colleagues from other disciplines
> * Teaches more junior engineers
> * Creates diagrams to document how the different parts of complex systems interact
> * Presents their own work clearly to stakeholders

**Comment by alicebartlett** [comment]
Let's discuss in our 3pm today

**Comment by alicebartlett** [comment]
Related issue about wording #94

**Comment by alicebartlett** [comment]
Clearly an issue with the first example here - it's just lightly reworded the original statement!

**Comment by lc512k** [comment]
addressed in https://github.com/Financial-Times/engineering-progression/pull/250
