### ISSUE TITLE
Feedback: S1->S2 delivery competencies

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#212]
From S1 workshop

- The first 2 competencies have a lot of overlap with some tech ones. Suggest that 'the delivery is taken out of the tech ones'
- Needs a competency around prioritising the team's work/backlog grooming (M->S1 has one about prioritising own work, so this would form a good thread)
- 'Is accountable for the delivery of the team (individually or jointly with other people), e.g.' - this feels like it should be split up as some examples feel big enough to be competencies in their own right, some of which would fit better under the communications section

**Comment by alicebartlett** [comment]
I think this is actually several issues, let's discuss in the 3pm meeting today.

**Comment by alicebartlett** [comment]
Delivery competencies for S1->S2

> Takes a stakeholder problem, investigates to understand it and proposes a solution

> Tackles complex cross-team technical issues breaking them down into smaller bits and addressing them, e.g.
> * Manages the roll out of a new shared tool to multiple code repositories, identifying what work needs to be done, and finding teams to do the work
> * Finds a bug in a library that affects multiple teams, fixes the bug and works with teams to make sure everybody is able to upgrade
> * Finds a manual process slowing down multiple teams and automates it

Tech competency for S1->S2

> Finds technical problems outside of immediate team and identifies ways to improve them, e.g.
> * Notices a lot of requests coming in to Ops Cops from Customer Support for an admin task that could be automated. Automates the task and works with the Customer Support team on how to use the new tool
> * While debugging an issue, traces the bug back to a shared library. Creates a patch for the bug and makes sure it is released.
> * Spots another team could benefit from using a security feature and helps them implement it

> Translates difficult business requirements into technical designs with stakeholders

**Comment by wheresrhys** [comment]
- Needs a competency around prioritising the team's work/backlog grooming (M->S1 has one about prioritising own work, so this would form a good thread)

This appears to have been addressed already

**Comment by alicebartlett** [comment]
I have . creared a new issue to address the first point: https://github.com/Financial-Times/engineering-progression/issues/244

**Comment by alicebartlett** [comment]
Regarding the final point: this is the competency- 

> Is accountable for the delivery of the team (individually or jointly with other people), e.g.

> * Helps delivery lead write progress reports
> * Writes a monthly update newsletter for stakeholders about recent releases
> * Grooms backlog to make sure issues are ready to be picked up
> * Makes sure new features are announced to interested parties (e.g. publishing on the appropriate slack channel, sending a release email)

**Comment by alicebartlett** [comment]
We should add better examples for actually _being accountable_ not _communicating about delivery_ which is what these are (except grooming the backlog)

**Comment by rowanmanning** [comment]
We've reopened two separate issues: #244 and #245
