### ISSUE TITLE
Provide examples for S1->S2 Identifies knowledge gaps within the team and gives training to address gaps

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#214]
From S1 workshop:

Activities such as reskilling a team feel like more Principal engineer level, so seems important to provide examples that set the right level

e.g.
- Running a workshop on a new build tool the team is planning on adopting, and collecting feedback to confirm understanding is good enough

**Comment by alicebartlett** [comment]
Agree.
I'll open a PR
