### ISSUE TITLE
Needs better 'fosters inclusive culture' thread

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#215]
From S1 workshop:

~'Takes ownership of' feels like too string a verb. Felt more comfortable with something like Actively fosters.~ RM: this part is done

There's a need for a thread from J -> principal

- J->M: demonstrates
- M->S1: models good behaviour
- S1->S2: actively fosters
- S2->P: takes ownership of/addresses problems with

Not sure if the above really works either

**Comment by alicebartlett** [comment]
I'm happy with "actively fosters" instead of "takes ownership". Does anybody else have any objections or comments?

**Comment by alicebartlett** [comment]
With regard to the rest of the thread we have this in J->M

**J->M Leadership**
> Positively contributes to an inclusive team culture, e.g.
> * Reminds others that team members may have child care duties
> * Draws people working remotely into planning conversations
> * Tactfully calls out exclusive or alienating behaviours from others
> * Organises a leaving collection for a colleague
> * Documents team norms to help new starters
> * Checks in with team members who appear stressed

Nothing in M->S1

**S1->S2**
> Takes ownership of ensuring an inclusive team culture, e.g.
> * Celebrates good work publicly and encourages the team to do the same
> * Spots problems between team members and helps to resolve them
> * Models inclusive behaviour to the rest of the team

And nothing in S2->P because we haven't written those yet, though I agree with you that there would be something in there about ownership.

**Comment by alicebartlett** [comment]
In regard to your suggestion, what is the difference between 
* J->M: demonstrates
* M->S1: Models

I would have said demonstrating and modelling are synonyms.

**Comment by wheresrhys** [comment]
They feel different to me. Kinda the same distinction between dressing well and being a model. Not something I feel strongly about though.

**Comment by rowanmanning** [comment]
We've decided not to add something for M–>S1 for this, as the J->M will still apply for those people. See #140
