### ISSUE TITLE
Feedback S1->S2: Shapes roadmap or priorities

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#217]
From S1 workshop:

This feels like it could fit under the Delivery section as worded. I feel the intent is more about setting the bigger picture though, so examples will help

**Comment by alicebartlett** [comment]
This competency is currently in the **leadership** section, and the full text is:

> Shapes roadmap or priorities (in collaboration with Product Owners if they work in a team with that role)

@wheresrhys Is the only issue that it feels miscategorised, or was there also some confusion about what types of evidence would meet this criteria?

**Comment by wheresrhys** [comment]
I think the impression was that it should be under leadership, but could possibly be reworded with more examples

Something like this

Shapes the medium to long term priorities of their team
- Finds commonalities between small feature ideas in order to form them into larger technical challenges for the team
- Champions turning things off into order to have capacity to work on new things

I find it really hard to think of examples that aren't too technical or vague, but I suppose the idea is to use your _technical insights_ to shape the priorities

**Comment by wheresrhys** [comment]
I created a PR with the above examples https://github.com/Financial-Times/engineering-progression/pull/249
