### ISSUE TITLE
Feedback Mid -> S1 Builds products ensuring they take adequate steps to protect user data

### ISSUE THREAD

**Issue by mark-barnes** [Financial-Times/engineering-progression#218]
From Mid workshop 
 This may not be applicable to all teams ... what if your team does not have userdata- does this need a "where applicable" in it 
  - could it be hanged to "protect sensitive data" . which could then include api keys etc....

**Comment by lc512k** [comment]
Addressed in https://github.com/Financial-Times/engineering-progression/pull/233
