### ISSUE TITLE
Feddback: Mid -> S1 Implements appropriate observability and monitoring when building a solution

### ISSUE THREAD

**Issue by mark-barnes** [Financial-Times/engineering-progression#219]

**Comment by mark-barnes** [comment]
From Mid workshop (part 2) 
what about working only on mature systems with monitoring set up 
  - add an example of cleaning up superfluous alerts as implementing appropriate... also maybe add  the word 'maintaining' to building

**Comment by lc512k** [comment]
I agree creating a dashboard from scratch may not be feasible in every project, but even for someone working on mature systems, this example surely applies, doesn’t it? 

```
Adds logging that is well-structured and captures useful information about the state of a system
```

I feel this competency is about creating and contributing to the data teams gather about their systems. I’m not sure the clearing up superfluous alerts quite fits with this. What do you think @mark-barnes ?

**Comment by mark-barnes** [comment]
@lc512k  -  think you are right.   In the session we were looking for the kind of work on monitoring or observability that someone might do to a mature system.    So thinking about improvements that someone might make .. which could include improving the noise to signal ratio by removing pointless slack/email alert spam :) 
that said the real problem was probably around the "building" ... we had some relatively new to mid level engineers thinking about how to get to S1 level.  They may not have had the chance to work on that many new systems and this issue is probably a product of that concern about getting that experience.   I would suggest by the time someone has spent a couple of years as a mid level and might be looking to go to S1 this concern will have disappeared.  It would be quite an edge case if someone had never done this going to s1 i think.    Personally i am happy to close this one

**Comment by wheresrhys** [comment]
In Q3/4 of this year security are asking for more structured logging, O&R may well start scoring quality of monitoring and nudging teams to improve, Tom Betts' team will also likely start agitating to add more monitoring around flows of data, and there are whole areas around request tracing that the FT has barely touched.

So to sum up, I would be surprised if, in any given year, there isn't _any_ opportunity to do something in this area, even on mature systems. 

And I've just realised I'm basically agreeing with what @mark-barnes said :joy:

**Comment by lc512k** [comment]
Ok, sounds like we’re good then. will close. Thanks both!
