### ISSUE TITLE
Feedback: M->S1 Manages technical trade-offs in the team's projects

### ISSUE THREAD

**Issue by mark-barnes** [Financial-Times/engineering-progression#221]
From Mid workshop (Part 2)  
maybe needs breaking down with examples, does this include deciding on when to refactor a piece of code ?... when is time to leave it (tech debt) and when is time to refactor it.  are small every day decisions enough for this ?

**Comment by lc512k** [comment]
Addressed in https://github.com/Financial-Times/engineering-progression/pull/235
