### ISSUE TITLE
Feedback: Mid->S1 Where appropriate, builds on other teams' work to solve problems,

### ISSUE THREAD

**Issue by mark-barnes** [Financial-Times/engineering-progression#223]
From mid workshop (part 2) 
Have we already got this one under the technical competencies .. why do we need this one?  does the biz ops example fit better in the examples for building resilience into things in technical
putting info into bizops feels like part of ""builds resilience into software or services"" - its about making sure the things is supportable.
how about we (re)move that example and try a different one here - maybe using tools created by the cloud enablement team ?  or learns from other teams about how they send data to splunk or graphite.   Are we trying to encourage behaviour that uses existing wheels rather than inventing new ones?

**Comment by lc512k** [comment]
addressed in https://github.com/Financial-Times/engineering-progression/pull/236
