### ISSUE TITLE
Feedback: mid ->S1 Has responsibility for others’ development through mentoring or line management

### ISSUE THREAD

**Issue by mark-barnes** [Financial-Times/engineering-progression#225]
From mid workshop (part 2)
if you are a mid level engineer in a small team there may not be opportunities to do this ... mentoring opportunities may not come along 
can we qualify this with something that make it more informal mentoring -   so perhaps example of helping onboard new starters/being a buddy for new starters ... finding people/more junior engineers outside your home team that need help/guidance.

**Comment by lc512k** [comment]
Addressed in https://github.com/Financial-Times/engineering-progression/pull/230
