### ISSUE TITLE
Add examples for being accountable

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/engineering-progression#245]
We should add better examples for actually being accountable not communicating about delivery which is what these are (except grooming the backlog):

> Is accountable for the delivery of the team (individually or jointly with other people), e.g.
> - Helps delivery lead write progress reports
> - Writes a monthly update newsletter for stakeholders about recent releases
> - Grooms backlog to make sure issues are ready to be picked up
> - Makes sure new features are announced to interested parties (e.g. publishing on the appropriate slack channel, sending a release email)

**Comment by wheresrhys** [comment]
Suggestion for an example:
- Writes measurable OKRs for the team

**Comment by alicebartlett** [comment]
I agree that this is a problem. I think we need some examples that are like -
"considers delivery timelines and keeps team on track"

**Comment by rowanmanning** [comment]
This has been floating around for a while. I think it needs doing before stable launch. Anyone want to volunteer?
