### ISSUE TITLE
Use of quantifiers (particularly 'regularly') in competencies and elsewhere

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#262]
For some competencies there is an unwritten expectation that it is an activity the employee will carry out regularly e.g fixing bugs, working on a delivery ticket

Others will most likely be rarer e.g. taking part in the hiring process, delivering a presentation.

In a handful of competencies (e.g. leadership section of J->M) the quantifier 'Regiularly' is used in the competency title.

Some ideas in response to all the above
- competencies that are about an activity that is carried out regularly should have 'regularly' in the title
- Could there be 2 classes of competency - regularly demonstrated and occasionally demonstrated - and we flag competencies as such, and make it clear the different expectations for evidence
- something else
- nothing

**Comment by rowanmanning** [comment]
I'd forgotten when we spoke about this in the session last week, but we do actually have the beginnings of something in the tone and language guide on this: https://github.com/Financial-Times/engineering-progression/blob/master/docs/language.md#use-frequency-qualifiers

**Comment by rowanmanning** [comment]
I'm OK with the idea of reviewing the competencies and adding quantifiers where necessary. I don't think we should codify this as a separate property on competencies though, however it might be nice to add more detail to the tone and language guide.

I don't want to do this work particularly. Any volunteers to do a review of how we use quantifiers?
