### ISSUE TITLE
Consider how we add supporting URLs to competencies

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/engineering-progression#276]
While working on the front-end domain-specific competencies, @alicebartlett and I wanted to add a link to the [FT Browser Support Policy](https://docs.google.com/document/d/1z6kecy_o9qHYIznTmqQ-IJqre72jhfd0nVa4JMsS7Q4/edit). There are some hurdles to adding this in a way that will ensure that it's _actually_ a link on the website and in the spreadsheet.

The original proposal for the data structure (#1) states:

> **No Markdown or formatting/links in any fields:** allowing this would mean that all tooling will have to parse these fields. This poses an issue for programs like Google Sheets, where only a full cell can be hyperlinked. It also adds an overhead for anyone processing the data

I think this still makes sense, but there is also a clear need to include supporting URLs in some competencies. E.g it may also be useful to link to the FT's line management or mentoring guidance from the competencies which mention these things.

My immediate thought is to propose adding a `supportingUrls` property to competencies which is an array of links, but there would be some work involved in making the URLs available on the website and in Google Sheets.

I guess I'd like further input from the working group on this, any thoughts?

**Comment by alicebartlett** [comment]
I agree with you, Rowan. Let's do this :+1:

**Comment by quarterto** [comment]
For Google Sheets, the array could be expanded into extra columns, after the description (since we can't have more than one URL per cell)

**Comment by quarterto** [comment]
this is fixed by #290 and #296
