### ISSUE TITLE
Improve transparency of promotions board

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/engineering-progression#291]
Related reading #288 

Right now, the decision making process of the promotions board is not written down anywhere in any form. This is not transparent. While I don't think it's possible to capture every nuance of the promotions board, right now I think we could do better.

This issue is to: 
- track any information we get back from the TLG about this (I sent them an email on Monday about it)
- When we get a response we'll update the progression website to either point to the right place, or include the information as appropriate.

Any information from the TLG that fits with the framework should also be incorporated into it.

**Comment by sbinlondon** [comment]
Any updates from TLG on this?

**Comment by alicebartlett** [comment]
@sbinlondon Nope!
