### ISSUE TITLE
Add data security competency

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/engineering-progression#299]
During our domain specific competencies work we added

> "Considers user privacy when building a system
- Knows the difference between personal and sensitive data as defined by GDPR
- Masks user data in logs and monitoring
- Uses restricted indexes in Splunk
- Stores the minimum amount of data required, for the minimum amount of time
- Builds in mechanisms that allow the FT to comply with Subject Access Requests
- Uses the correct cache-control directives to ensure user privacy"
- Knows and applies FT approved data retention policies

But these are actually applicable to all software engineers. This issue is to propose we add this competency to the Mid -> Senior 1 level. 

cc @elenageorgievaft @mark-barnes

**Comment by rowanmanning** [comment]
Reopening, we probably should have disabled stale bot while we were on hiatus.

**Comment by rowanmanning** [comment]
Covered by [272be0d0-6b55-11e9-ae4e-0583f673f115](https://github.com/Financial-Times/engineering-progression/blob/main/data/competencies.yml#L379)
