### ISSUE TITLE
Rename levels from "x to y" to "y"

### ISSUE THREAD

**Issue by apaleslimghost** [Financial-Times/engineering-progression#304]
i.e. rename `Junior to Mid` to `Mid`, `Mid to Senior 1` to `Senior` etc

the competencies are meant to represent expectations of each level of engineer. they're not about promotion, so it doesn't make sense to name them after the transition between levels.

**Comment by rowanmanning** [comment]
Reopening, we probably should have disabled stale bot while we were on hiatus.

**Comment by rowanmanning** [comment]
I think we should do this work before the Principal Engineer competencies happen. I'm going to do this unless anyone objects or wants to do this themselves?
