### ISSUE TITLE
Add competencies for Juniors

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/engineering-progression#305]
If the proposal to rename competency levels in #304 happens (I think it should), then we should also consider adding competencies for juniors. As the competencies are meant to represent expectations of each level of engineer, it feels like juniors are missing out.

Also, since this framework was created, some groups at the FT have started using the competencies to guide hiring. It would be useful for those groups to also have some competencies to base hiring junior engineers on.

**Comment by robgodfrey-ft** [comment]
So my understanding is that junior to mid competencies are for juniors looking to progress to mid. Who would a set of junior competencies be targetted at? Do we have individuals pre-junior looking to progress to junior?

**Comment by pixelandpage** [comment]
@robgodfrey-ft I think the Junior competencies would mainly be useful for recruitment decisions, rather than promotions ones, but if we do have any pre-Junior engineers then they should be able to use the framework to track their progress the same way we do for the other levels. We should keep this in mind when drafting the competencies 🙂

**Comment by rowanmanning** [comment]
Thanks @robgodfrey-ft, good question 🙂

So based on the first proposal (#304) the "Junior to Mid" competencies will be renamed to just "Mid", then these competencies have a more clear dual use:

1. They can be used by Mid Engineers and their line managers to help see where they might need to progress, and where their strengths and weaknesses are
2. They can be used by Junior Engineers and their line managers to see what would be expected of them at the next level of seniority

So introducing new Junior competencies won't really cover point 2 unless we take on more graduates or pre-Junior people, but they _will_ be useful for point 1 – existing Juniors and their line managers will have a framework to discuss their work and career.

**Comment by jenniferemshepherd** [comment]
In my mind, it makes sense to have competencies for every level.  That way at PDR time it's very clear whether you are performing above, at or below expectations.  They are also useful re: progression of course, but only really to tell you if you are performing at a level above your current role.

**Comment by robgodfrey-ft** [comment]
I agree having a set of junior competencies for evaluating junior hires against makes a lot of sense.

I can see you might use the mid set of competencies to initially evaluate a new mid hire to see if there are any gaps to work on. For those promoted from junior to mid, there may be a few gaps to address but I would expect them to have already demonstrated many of the mid level competencies as that is a requirement for promotion. Therefore for promoted mids I would expect them to start looking towards the next level (i.e. senior) competencies. 

For PDRs I have a slightly different viewpoint. Some objectives will be based on progression against competencies for sure, however others will be based on delivery of specific outcomes not necessarily related to specific competencies. So progression against competencies will have some bearing but is only part of the picture in my view.

**Comment by mark-barnes** [comment]
Hi @robgodfrey-ft 
We discussed this issue today and there was one thing that we want to clarify regarding this part of the comment.
 _I would expect them to have already demonstrated many of the mid level competencies as that is a requirement for promotion._ 

The competencies are not intended to be a checklist in the sense that ticking off each one does not guarantee promotion and in addition not fulfilling all of them may not be a barrier to promotion.  From the "how to use section" 
_They are not a checklist, but a way to indicate what areas they may need to improve in._ 

The Engineering competencies are used to inform conversations about career progression between an engineer and their line manager.    Basically it is up to an individual, their line manager and their technical director to use these competencies together with other evidence (such as 360 feedback etc)  when thinking about their career progression.
Please get back to us if you want to discuss.

**Comment by robgodfrey-ft** [comment]
I did say many not all :) I take the point that the competencies should not be used as a crutch. 

However what I am still a little confused about is that today "Junior to Mid" describes a set of competencies for junior engineers to work with their line managers on. By renaming to "Mid" and then using that as a set of competencies for mid level of engineers is there a shift right in competencies happening. Rowan earlier stated "They can be used by Mid Engineers and their line managers to help see where they might need to progress, and where their strengths and weaknesses are". As I said a little confused at the moment

**Comment by rowanmanning** [comment]
Hi Rob, sorry for the confusion. So if a Junior can be promoted to a Mid without meeting _all_ of the competencies, then those competencies are still useful for a Mid to identify potential gaps in their knowledge. Is that a better way to phrase it?

This would be the case still if we kept the "Junior to Mid" naming, you can see each of the current competency levels as useful to engineers with either of the titles. Does that make sense? Happy to meet in person if I'm not getting this across well with written words 🙂

**Comment by robgodfrey-ft** [comment]
I did say many not all :) I take the point that the competencies should not be used as a crutch. 

However what I am still a little confused about is that today "Junior to Mid" describes a set of competencies for junior engineers to work with their line managers on. By renaming to "Mid" and then using that as a set of competencies for mid level of engineers is there a shift right in competencies happening. Rowan earlier stated "They can be used by Mid Engineers and their line managers to help see where they might need to progress, and where their strengths and weaknesses are". As I said a little confused at the moment

**Comment by robgodfrey-ft** [comment]
OK that makes sense. I think my interpretation is that for a new hire or someone newly promoted to a mid engineer role, you may use the mid level competencies for some time to ensure a solid foundation as a mid engineer before progressing to look at the senior 1 competencies and working towards promotion.

**Comment by rowanmanning** [comment]
Reopening, we probably should have disabled stale bot while we were on hiatus.

**Comment by mark-barnes** [comment]
**Update from Mark, Katie and Tash meeting**
Having discussed this it is unclear what the purpose of creating competencies for junior engineers is. We would advise against the use of them during hiring as juniors are predominantly hired based on an assessment of potential and are often from very different backgrounds in terms of skills and experience levels.In addition we feel writing competencies for Juniors may make people feel the reverse of what this is trying to achieve. We want to make Juniors feel supported and writing a set of competencies for a newly started Junior may make confidence levels drop. A better tool for setting expectations and measuring progress are probation objectives that may vary from person to person, depending on background and experience.Support for junior engineers is vital and should be part of line management training. 
We propose we don't do this.

**Comment by mark-barnes** [comment]
It may be helpful to have some common hiring practices for juniors across engineering  - but it is not the role of these competences to define that - closing this issue
