### ISSUE TITLE
Explicitly add there is not an expected timeline for career progression?

### ISSUE THREAD

**Issue by mark-barnes** [Financial-Times/engineering-progression#306]
should there be an explicit call out in the FAQ that there are not timelines for promotions on the competencies?
what i mean is you don't have to be a junior for N months/years before you are allowed to be a mid.  equally just because you have been a mid for N years that does not mean you automatically get a promotion.

**Comment by mark-barnes** [comment]
this issue came up while organising the domain specific workshop for infra engineers

**Comment by rowanmanning** [comment]
I think this makes sense to add. We're not taking on any extra responsibility or decision making by including this line, and it sounds like it will be clarifying for someone.

I think we'd need to word it carefully though, as we've been deliberately trying to move the language we use away from promotions.

**Comment by apaleslimghost** [comment]
As discussed in the working group, it is not in the remit of the Engineering Progression framework to outline what is and isn't expected for timelines of promotion. This should be for technical leadership and line managers to communicate
