### ISSUE TITLE
Can we have examples for a competency to show non-extroverts could do it too

### ISSUE THREAD

**Issue by mark-barnes** [Financial-Times/engineering-progression#311]
_"Finds technical problems outside of immediate team and identifies ways to improve them, e.g.
"_

We need examples that allow for people that are not extroverts to fulfill this one.   This may be interpreted as something that people that network well can do far more easily than people that don't

- one possible suggestion from the workshop was going on a secondment and helping another team deliver something

**Comment by rowanmanning** [comment]
After discussion in the working group, we think the current examples aren't _particularly_ extrovert-centric, especially when you consider that these are behaviours that we expect of a Senior 2:

- Notices a lot of requests coming in to Ops Cops from Customer Support for an admin task that could be automated. Automates the task and works with the Customer Support team on how to use the new tool
- While debugging an issue, traces the bug back to a shared library. Creates a patch for the bug and makes sure it is released.
- Spots another team could benefit from using a security feature and helps them implement it

The thing we're trying to capture here is somebody finding a problem outside of their immediate area, fixing it, and letting people know that it's been fixed via whichever means they feel comfortable with.

We're going to close this, but if there are some improvements that could be made to clarify this then we can reopen.
