### ISSUE TITLE
Reword "does not duplicate work of other teams"  to be positive

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/engineering-progression#53]
Competency ID is: 9e1a0313-f602-4786-97c6-d4d49506f0bb
"Does not duplicate work of other teams" is something an activity phrased in the negative, ie "Do not do this". 

It would be better if we could find a positive phrasing of this eg "re-uses and improves on other teams work instead of duplicating effort"

This competency is specifically around the idea that people prefer to build their own thing than engage with others who have already started on something

**Comment by wheresrhys** [comment]
Where appropriate, builds on other teams' work to solve problems 

Examples
- Uses origami components to style a web page
- Records information about technical infrastructure in Biz Ops

??

**Comment by rowanmanning** [comment]
Sounds good, let's go with Rhys' suggestion

**Comment by rowanmanning** [comment]
Addressed in #135
