### ISSUE TITLE
Make "Understands and considers other teams' needs" mode concrete

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/engineering-progression#54]
This is difficult to provide evidence for so I'd like to make it more concrete. The competency is about not working within a silo, but appreciating and balancing other teams priorities.

competency id is: d8651fc0-059b-4c11-929f-e07803f9f8bf

**Comment by wheresrhys** [comment]
Actively seeks the views of other teams to help guide work

??

**Comment by alicebartlett** [comment]
Good suggestion, thanks Rhys!
