### ISSUE TITLE
Consider improvements to the competencies page

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/engineering-progression#71]
The [competencies page on the website](https://engineering-progression.ft.com/competencies/) had a nice overhaul in #68, but possibly the documentation layout isn't ideal for this. I think we should consider the following:

1. Should this be one page, or should we actually have a different page for each level? My assumption is that somebody reading this information cares mostly about one level at a time – either the one that they're working towards or the one that their report is working towards. It may be nice to be able to link someone more directly to a competency, e.g. `https://engineering-progression.ft.com/competencies/junior-to-mid/`

2. Are one of the other [o-layout](https://github.com/Financial-Times/o-layout) layouts a better choice for this page? E.g. the [landing layout](https://www.ft.com/__origami/service/build/v2/demos/o-layout@3.1.6/landing-layout?brand=internal) but without a hero, or the [query layout](https://www.ft.com/__origami/service/build/v2/demos/o-layout@3.1.6/query-layout?brand=internal)

**Comment by wheresrhys** [comment]
This is done, no? @rowanmanning

**Comment by rowanmanning** [comment]
Oh, yep
