### ISSUE TITLE
Define the competency domains

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/engineering-progression#8]
Currently each competency has a `domain` property to indicate whether it is only required for a specific domain in engineering. If this field is `null` then it signifies that the competency applies to all domains, otherwise it is a freeform string. In the catchup on 2019/02/20 we decided that we should define these domains. Let's do that here.

From the Google doc:
> We need to define some “domains” for the domain specific knowledge
>   - Web engineer
>   - Operations engineer
>   - We have one senior engineer in the apps team whose area of expertise is Swift

**Comment by rowanmanning** [comment]
The Beta milestone is also looking a little too close to get anything meaningful ready regarding competency domains. We're moving out of this milestone and will revise a timeframe once the beta has shipped.

**Comment by alicebartlett** [comment]
@rowanmanning and I have started looking at this - we'll be producing a draft of competencies for "backend" and "frontend", which we will circulate for feedback next week.

**Comment by mark-barnes** [comment]
The engineering competencies framework working group are considering closing this issue. 

We have run workshops/focus groups with a number of engineers.   
We went through the existing technical competencies in detail and we have not found compelling reasons to create additional sub categories of domain specific competencies.  

We have had some very good suggestions for improvements to the competencies and the examples associated with them to help engineers from all domains/disciplines use them.   
Those suggestions will be dealt with as pull requests and issues for visibility and to improve this competency framework for all engineers using them.

We are going to leave this issue open for two weeks to allow feedback/questions/comments.   Then, providing there no new compelling reasons for keeping this issue open come up, we will close it 
:) 
So closing date for comments is Tuesday 25th February 2020.

**Comment by sjwells** [comment]
I think we need to work out whether being able to display all competencies at a particular level represents being ready for promotion. My sense is that people are being asked to do more, to display mastery of particular technologies or to demonstrate impact in particular areas. I wonder whether domain-specific competencies are applicable there. 

I also wonder whether others agree that promotion is not *solely* about having achieved a set of competencies?

**Comment by apaleslimghost** [comment]
> promotion is not solely about having achieved a set of competencies

this is our intention for the framework, and we've been trying recently to reword things so people hopefully don't assume that (see #303). i believe there's also some documentation about the process that's being drafted by HR, which includes the competencies, but only as _one_ of the things that _could_ be looked at in a promotions case.

**Comment by alicebartlett** [comment]
@sjwells could you clarify this point?

> I think we need to work out whether being able to display all competencies at a particular level represents being ready for promotion. My sense is that people are being asked to do more, to display mastery of particular technologies or to demonstrate impact in particular areas. I wonder whether domain-specific competencies are applicable there.

We're not sure if you mean that 

> More [domain specific] competencies = more things required fo engineers
or
> More [domain specific] competencies = fewer more specific things required of engineers

**Comment by sjwells** [comment]
I was saying that *if* the competencies represent everything you need for promotion, then we would need to have domain specific competencies. 

But, I think the answer is that they are part of showing you're ready and that you are making that clearer. In which case, I think you don't need domain-specific competencies. Maybe what would be good is to ask people to discuss other competencies with their manager to work out what else they need to be good at in their specific role and team?

**Comment by rowanmanning** [comment]
> Maybe what would be good is to ask people to discuss other competencies with their manager to work out what else they need to be good at in their specific role and team?

We should add an FAQ around this, I've opened an issue here: #318

Going to close this issue. Thanks for your feedback, Sarah 🙂
