### ISSUE TITLE
Reflections on Junior -> Mid Progression Competencies

### ISSUE THREAD

**Issue by jenniferemshepherd** [Financial-Times/engineering-progression#80]
Much more helpful than the previous matrix.  Love the tick list and percentage thing via spreadsheet.  Feels very clear and (generally) obvious how to evidence things.  Seems like a reasonable set of requirements for a mid-level engineer.

1. `Regularly fixes security issues raised by others/automation in own code`: wording is unclear to me.  Does it mean: 
    - `Regularly fixes security issues raised by others/Regularly fixes automation in own code` or
    - `Regularly fixes security issues raised by others/Regularly fixes security issues raised by automation in own code`?
2.  Nothing covers any certification, training or conference contributions; perhaps this is covered by `Takes ownership of personal development`?
3.  `"Uses user research or data to inform decisions, e.g. Attends customer based user research for a feature being worked on OR Sets up some guerilla testing with developers for a new bit of tooling"` - think an opportunity would need creating purely for the purpose of ticking this.
4. `"Has knowledge of at least one other area of the FT outside technology, e.g. Can articulate the editorial workflow OR Knows what's important to finance"` - again, think an opportunity would need creating purely for the purpose of ticking this.

**Comment by wheresrhys** [comment]
Re 3 & 4, thinking back to a few years ago, opportunities for these were fairly normal, but ad hoc. In particular, for the second one we got someone from editorial to talk us through how they worked once the team took on more than ~10 new people. Maybe we can suggest to FT learning & development that they facilitate regular cross-department knowledge sharing.

**Comment by alicebartlett** [comment]
Thanks for raising this issue Jennifer! This is exactly the kind of feedback we're looking for ^_^

I think as there are four separate issues here it might be useful to break them out for discussion. I'm going to do that now.

**Comment by j-mes** [comment]
2. is quite vague to me too.

By conference contributions: What does this mean? 
* Attending, volunteering or speaking?
* What counts and what does not count?

3. Guerilla testing - Another tech industry term that's not painfully obvious either to someone that does not have English as a first language.

> Guerrilla Testing means going into a coffee shop or another public place to ask people there about your product or prototype. It can be conducted anywhere ex- cafe, library, train station etc, essentially anywhere where there is significant footfall.

In this case, if it's a new tool, other developers/engineers. I had to google the term 'guerrilla testing'. 

Maybe the language could be changed to be more clear as well, especially for Juniors that are coming into the tech industry and would not potentially be up to scratch with all the tech terms being used i.e. rubber ducking, shaving a yak, bike shedding etc. To a non-tech person it's like 'wtf does that mean?' (Pardon the language by the way)

**Comment by alicebartlett** [comment]
Closing - please refer to #81, #82, #83 and #84 for discussion in each competency
