### ISSUE TITLE
J->M feedback on security fixes competency

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/engineering-progression#81]
(Breaking #80 out into four separate issues for discussion)

1. `Regularly fixes security issues raised by others/automation in own code`: wording is unclear to me.  Does it mean: 
    - `Regularly fixes security issues raised by others/Regularly fixes automation in own code` or
    - `Regularly fixes security issues raised by others/Regularly fixes security issues raised by automation in own code`?

**Comment by rowanmanning** [comment]
This has been updated (#86), and it now reads:
> Regularly fixes security issues raised by others (or raised by automation) in own code

@jenniferemshepherd thanks for raising! I'm gonna close this issue, but if you still think it needs work then happy to reopen.

**Comment by sbinlondon** [comment]
Sorry to reopen this - I was interested in a bit more clarification.

Do you mean security issues i.e. vulnerabilities raised by Snyk? Could you give a more concrete example? It still feels a bit vague.

**Comment by alicebartlett** [comment]
We mean any kind of security vulnerability - could be from Snyk, could be found by the cyber security team, you could have found it yourself.
I'll add some examples.
