### ISSUE TITLE
J->M feedback on User Research/data competency

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/engineering-progression#83]
(Breaking out #80 into four separate issues)

3.  `"Uses user research or data to inform decisions, e.g. Attends customer based user research for a feature being worked on OR Sets up some guerilla testing with developers for a new bit of tooling"` - think an opportunity would need creating purely for the purpose of ticking this.

**Comment by j-mes** [comment]
From #80 

Guerilla testing - Another tech industry term that's not painfully obvious either to someone that does not have English as a first language.

> Guerrilla Testing means going into a coffee shop or another public place to ask people there about your product or prototype. It can be conducted anywhere ex- cafe, library, train station etc, essentially anywhere where there is significant footfall.

In this case, if it's a new tool, other developers/engineers. I had to google the term 'guerrilla testing' as I was not aware of this saying/method. 

Maybe the language could be changed to be more clear as well, especially for Juniors that are coming into the tech industry and would not potentially be up to scratch with all the tech terms being used i.e. rubber ducking, shaving a yak, bike shedding etc. To a non-tech person it's like 'wtf does that mean?' (Pardon the language by the way)

**Comment by jenniferemshepherd** [comment]
💯 `rubber ducking, shaving a yak, bike shedding`

**Comment by rowanmanning** [comment]
This has been addressed in (#88), and now has some reworded examples:

> **Uses user research or data to inform decisions**, e.g.
>  - Attends customer based user research for a feature being worked on
>  - Sets up a testing session with peers for a new bit of tooling
>  - Finds a common pain point among teammates and proposes/builds a solution for it

We agree on the poor choice of language – we have a [section in our tone and language guide](https://github.com/Financial-Times/engineering-progression/blob/master/docs/language.md#avoid-metaphors-or-colloquialisms) to help guide us away from wording that excludes people without English as a first language, but we still miss the occasional one!

Thanks @jenniferemshepherd for raising and @j-mes for the feedback 🙂 I'm gonna close this, if you still have any issues with this then we can reopen.
