### ISSUE TITLE
J->M feedback on cross business knowledge

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/engineering-progression#84]
(Breaking #80 out into separate issues for discussion)
4. `"Has knowledge of at least one other area of the FT outside technology, e.g. Can articulate the editorial workflow OR Knows what's important to finance"` - again, think an opportunity would need creating purely for the purpose of ticking this.

**Comment by sbinlondon** [comment]
I think it would be really cool to organise some one-off events around this. Perhaps in place of (or in addition to) one of the Tech Talks every so often, we can invite someone from another area of the business to come and talk about what they do? I for one would definitely be interested in the _editorial workflow_ example, learning how a breaking story goes from tip off to paper. Happy to help organise this if people would be interested?

**Comment by lc512k** [comment]
@Financial-Times/engineering-progression-working-group I propose we move this to M->S1, swapping it for "has worked with or in a other team". More realistic to expect a junior engineer to have done a bootcamp on another technical team and a mid level engineer to have gone beyond that and gained knowledge about other parts of the business. 

By mid level its more reasonable to expect you'll have engaged with your stakeholder enough to understand their process. For people in the minority who don't have a direct stakeholder or their stakeholder is in tech, an example could be a non technical bootcamp or shadowing someone relevant in another area

**Comment by wheresrhys** [comment]
From memory, I think j-m we were thinking that it’s about knowing what another team does, whereas m-s it’s about being appreciative of different ways of working, but I agree that, as worded, it feels very backward.

Maybe something like this (in spirit - my wording is naff) 
- j-m - Understands which teams their team interacts with and why, and can make sensible decisions about when to involve them
- m-s - Understands where their team fits in to the broader FT context, and is able to adjust to other teams' ways of working, schedules etc

**Comment by sbinlondon** [comment]
I agree with your summary @lc512k. I think it's important for juniors to come away with a holistic sense of what goes on in P&T on other teams, which bootcamps and secondments can offer.

@wheresrhys I think your wording definitely captures a different spirit to the original competency and think it's a step in the right direction. Do we combine this with something about wider P&T knowledge/bootcamps, or make them separate competencies, or something else?

**Comment by alicebartlett** [comment]
[24/04/19] Assigning myself to resolve. Will post an update.

**Comment by alicebartlett** [comment]
OK, my proposal is 
- we remove this competency as it is very difficult to fulfill at any level
- move the one about bootcamps (currently in m->s1) down into j->m.

**Reasoning**
The thing we are aiming to promote here is engineers having a well rounded view of the company, not just their own team.

We do this using bootcamps and secondments to help engineers understand the rest of technology. For engineers understanding the rest of the business there are no official mechanisms, but experience is usually gained ad-hoc because teams don't generally work in isolation.

in M-> S1 we already have a competency about working with other teams through bootcamps or o&r
```
Has worked with in or with another team, e.g.

- Has done a three month secondment with Operations and Reliability
- Has done a bootcamp with another team
```
I think we should move this to J->M and clarify the wording to:
```
J->M
Has worked with teams outside of their home group (Where home group will be one of Customer Products, FT Core, Internal Products, Operations and Reliability,  Enterprise Services and Security and FT Group Products and FT Labs)
- Based in Customer Products but collaborated with developers from FT Core to build a new API endpoint for content
- Has done a bootcamp with another group
- Had done a secondment to Operations and Reliability"
```

I think we leave out anything about understanding other aspects of the business entirely, because they are:
- diffiuclt to prove eg "understands publishing workflow" is not easy to provide concrete evidence for
- difficult to achieve "understands what is important to finance" - what does this even mean? there are not a lot of natural opportunities for most developers to gain this understanding.
