### ISSUE TITLE
clarification on improving delivery process

### ISSUE THREAD

**Issue by cebirmingham** [Financial-Times/engineering-progression#90]
I think I'd find `Improves delivery process and encourages others to do the same` in Mid-Senior 1 difficult to meet. The only example given (`Updates the scrum process to fit the changing needs of the team`) seems to be more the role of the delivery lead.

Are there any other examples that would suit teams which have delivery leads, or does this only apply to teams where engineers manage delivery?

**Comment by rowanmanning** [comment]
Sorry we haven't got back to you on this! A couple of points which weren't written down when you opened this issue:

1. All competencies apply to everyone (unless they're domain-specific, e.g. knowing CSS only applies to engineers who build websites)
2. The examples in competencies are illustrations of _one_ way you could meet the competency, not the only way

These are now documented on the website in a [how to use guide](https://engineering-progression.ft.com/competencies/how-to-use/).

I understand the point you raised about the role of a delivery lead, and the one example given would be easier to meet in a team that doesn't have one. I think we need to add some more examples to this competency which explain how to meet it in collaboration with a delivery lead, and also how to improve the process in ways that a delivery lead can't.

**Comment by alicebartlett** [comment]
[24/04/19] 
@rowanmanning has released instructions that clarify how to use the examples.

Suggestions for more examples:
* Champions technical issues that effect delivery such as release cycles, dealing with tech debt and bug fixes
* Encourages other engineers to participate in agile team rituals

@cebirmingham what do you think of these clarifying examples?
