### ISSUE TITLE
Print friendly version of the page

### ISSUE THREAD

**Issue by OttlikG** [Financial-Times/engineering-progression#92]
Implementing a print style could be something others can benefit from.
I had to use the google spreadsheet to generate a printable pdf.

**Comment by rowanmanning** [comment]
Thanks for raising this, Gabor. This can possibly be done alongside #71, which outlines some potential updates to the competencies page.

**Comment by OttlikG** [comment]
Sounds good.

**Comment by rowanmanning** [comment]
We've moved this into the launch milestone. I think it's important, but it shouldn't block us from reaching beta. Happy to review a PR if someone else wants to take this on.
