### ISSUE TITLE
Language clarification for debugging complex issues at speed

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/engineering-progression#94]
_Opened on behalf of @JakeChampion after we ran through the competencies._

---

**Competency:** `d6e3e7d1-1a53-444d-80ad-0240775a028d` (S1→S2, Technical)
> Debugs and fixes complex bugs at speed…

What's meant by "complex", and who judges what is complex? What's meant by "speed"?

**Comment by wheresrhys** [comment]
As engineers I think recognising complexity is part of doing the job once you get senior; hard to define, but once you've got to the point where you're managing a senior1 -> senior2 candidate, I would hope you'd be able to recognise a complex bug, and I'd hope that any technical members of the promotions board could too. Asking these competencies to define complexity is probably too hard. Some examples would help though

Maybe speed should be changed to efficiently? Capturing that its' about getting to the nub of the problem, and fixing it without going down loads of unnecessary blind alleys

**Comment by rowanmanning** [comment]
We could use some examples here, but we think that somebody who's line-managing an S1–>S2 candidate should have a clear understanding of what a "complex" issue or bug is. The "at speed" part we should change to "efficiently"

**Comment by alicebartlett** [comment]
[24/04/19] Suggestion:

Debugs and fixes complex bugs ~at speed~ efficiently
* Investigates a discrepancy in reported ad traffic. Works with the ad ops team to narrow down scope of problem. Uses technical knowledge to consult logs for various systems. Identifies a fix and implements.
* Investigates a drop in organic traffic from google, makes educated investigations into various aspects of the end to end system, consulting other domain experts along the way and keeping stakeholders aware of progress.

**Comment by alicebartlett** [comment]
Do we need to look at this competency end-to-end as well? we have a similar competency earlier on.
