### ISSUE TITLE
Reword "improve" to "solve"?

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/engineering-progression#95]
_Opened on behalf of @JakeChampion after we ran through the competencies._

---

**Competency:** `a8571c7f-296d-47ab-acad-d1b90b5a9391` (S1→S2, Technical)
> Finds technical problems outside of immediate team and identifies ways to improve them…

Should "improve" be "solve"? Improving technical problems reads like you're making the problem worse.

**Comment by wheresrhys** [comment]
Identifies and addresses technical problems outside of immediate team

**Comment by alicebartlett** [comment]
I disagree that "improve a problem" means "make a problem worse"

What is the opposite of "improve"? "worsen"? So if you "worsen a problem" do you make it better or worse?

**Comment by alicebartlett** [comment]
Re-closing as this was re-opened by accident
