### ISSUE TITLE
Some clarification around technical considerations and stakeholders

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/engineering-progression#96]
_Opened on behalf of @JakeChampion after we ran through the competencies._

---

**Competency:** `f7045590-960d-4a08-b2d6-db6dcff463d6` (S1→S2, Communication)
> When working on a complex problem, is able to break down technical considerations clearly for stakeholders…

Sometimes stakeholders are tech people (as in Origami), which means that this competency seems easier to achieve. Is that OK? Also would an opportunity need to be created for someone to meet this if they're not a tech lead?

**Comment by wheresrhys** [comment]
Good point.

It's certainly a different skill, but I'm not sure it's any easier; a tech audience will demand more detail - sometimes boiling things down to some high level ideas for non techies is actually easier cf. we should store everything in a connected graph vs a graphQL API is the right solution

My gut feeling is that this can remain a single competency, but I'm not tied to that appraisal

**Comment by alicebartlett** [comment]
Some discussion about what this means - what we're trying to capture is that someone can explain complicated problems to different people, and is able to vary the way the describe it depending on who they are talking to. Let's remove the 'stakeholder' part to make this broader as it doesn't have to be a stakeholder.

Worth checking the previous competencies in this thread to make sure this still makes sense cross level.

When working on a complex problem, is able to break down technical considerations clearly. ~for stakeholders~

**Comment by rowanmanning** [comment]
I've reviewed all the competencies we have around communicating to non-technical colleagues. This is the full picture. This is a bit of a mess. I'm going to open a PR with some suggestions, I think generally we should keep one in communication and one in leadership for each level.

## Junior to Mid

**ID:** `88c876aa-fce5-414b-b0c0-b1b7602beea8`
**Area:** Leadership

> Presents their work to a product owner or tech lead. Clearly communicates technical concepts to non-technical colleagues.


## Mid to Senior 1

**ID:** `efc4ba84-9188-40cf-97c8-b61da4b163e3`
**Area:** Communication

> Communicates technical concepts to non-technical people clearly

---

**ID:** `11d32a45-ea1e-411f-a810-12a4f0b8ddb9`
**Area:** Leadership

> Presents their work to stakeholders. Clearly communicates technical concepts to non-technical colleagues.

---

**ID:** `c0cf9ac1-a25f-44ed-818e-ba0895dc5e02`
**Area:** Leadership

> Presents aspects of their work to stakeholders


## Senior 1 to Senior 2

**ID:** `f7045590-960d-4a08-b2d6-db6dcff463d6`
**Area:** Communication

> When working on a complex problem, is able to break down technical considerations clearly for stakeholders

---

**ID:** `60fc5d33-a5ee-4c1b-a370-e0c8a6b8ada9`
**Area:** Leadership

> Presents the team's work beyond their immediate team to stakeholders. Clearly communicates technical concepts to non-technical colleagues
>   - Speaks at the Technology All Hands
>   - Writes one-pagers to explain technical descisions
>   - Writes a blog post about an aspect of the team's work
