### ISSUE TITLE
Issue with meeting the "leads hiring" competency

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/engineering-progression#97]
_Opened on behalf of @JakeChampion after we ran through the competencies._

---

**Competency:** `6942e402-72ff-43ee-ae16-b4c1b17ff92f` (S1→S2, Communication)
> Leads hiring process for new Engineers…

This would be difficult to meet for someone on Origami, who hasn't done any hiring for over a year. This would be fine for `7cf4de83-f8e0-4311-ba1b-a9233c659520` (_Contributes_ to hiring process), as we'd work with another team to create the opportunity; however it's very unlikely that another team would be fine with someone external coming along to _lead_ a hiring process.

**Comment by alicebartlett** [comment]
Hmm - very valid point. I vote we remove this competency entirely. What does anyone else think?

**Comment by rowanmanning** [comment]
Let's remove this, but see if we can add hiring as an example on any other competencies – it'd be good for participation in hiring to still be recognised. We need to make sure that we remove _all_ of the hiring competencies as part of this work

**Comment by rowanmanning** [comment]
U-turn. We're not removing this competency, we are changing the requirement that all competencies must be met. I'll close this once the "how to use" has been updated

**Comment by rowanmanning** [comment]
How-to guide update has been deployed as part of #133. In this particular case, Origami hasn't done any hiring for over a year so this wouldn't be counted against a promotions case
