### ISSUE TITLE
Examples needed for "tackles complex cross-team issues" competency

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/engineering-progression#99]
_Opened on behalf of @JakeChampion after we ran through the competencies._

---

**Competency:** `83b06961-6462-4500-8ff5-9381f7de8dc5` (S1→S2, Delivery)
> Tackles complex cross-team technical issues breaking them down into smaller bits and addressing them…

Some examples would be useful for this. We struggled to work out where the opportunity to do this would be in some teams.

**Comment by alicebartlett** [comment]
Something like this?:

- Finds a bug in a library that affects multiple teams, fixes the bug and works with teams to make sure everybody is able to upgrade

**Comment by rowanmanning** [comment]
Moving to the Beta milestone, as this wasn't completed before the workshops.

**Comment by alicebartlett** [comment]
@JakeChampion does my suggestion work for you?

**Comment by JakeChampion** [comment]
It does 👍
